### ISSUE TITLE
Failed to install in Per Cell version

### ISSUE THREAD

**Issue by dixonsiu** [personium/ansible#80] opened 2019-02-21 15:15 UTC
Similar [issue](https://github.com/personium/setup-vagrant/issues/42) in setup-vagrant

**Comment by tochi-y** [comment] 2019-10-23 08:21
Per Cell version works normally on public cloud. Maybe other cause or setup-vagrant issue.

**Comment by shimono** [comment] 2022-06-24 05:34
We close this issue since this seems to be caused by an external reason.
If any specific issue is spotted, please reopen this issue and add more details.

**Closed by shimono** 2022-06-24 05:34 UTC
Labels: enhancement
